
plot.orientation( ...
    'rottweiler', 'german_shepherd', 'malamute', 'dalmatian', ...
    'doberman', 'husky', 'golden_retriever', 'corgi', 'pug', ...
    'poodle', 'collie', 'border_collie');
export.fourbythree('results/orient_dogs')
close all

plot.orientation( ...
    'cat', 'lion', 'tiger', 'leopard', 'snow_leopard', 'cheetah', ...
    'jaguar', 'lynx', 'sphinx', 'ocelot');
export.fourbythree('results/orient_felines')
close all

plot.orientation( ...
    {'horse', 'my_little_pony'}, {'donkey', 'my_little_pony'}, ...
    {'pony', 'my_little_pony'}, {'unicorn', 'my_little_pony'}, ...
    {'pegasus', 'my_little_pony'}, {'winged_unicorn', 'my_little_pony'}, ...
    {'zebra', 'my_little_pony'});
export.fourbythree('results/orient_equines')
close all

plot.orientation( ...
    'wolf', 'coyote', 'husky', 'fox', 'folf');
export.fourbythree('results/orient_canines')
close all

plot.orientation( ...
    'flareon', 'jolteon', 'vaporeon', 'umbreon', 'sylveon', ...
    'espeon', 'glaceon', 'leafeon', 'eevee');
export.fourbythree('results/orient_eevolutions')
close all

plot.orientation('bulbasaur', 'charmander', 'squirtle');
export.fourbythree('results/orient_starter_pkmn')
close all

